// HPSWrapper_arm_hps_hps_io.v

// This file was auto-generated from altera_hps_io_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 17.1 593

`timescale 1 ps / 1 ps
module HPSWrapper_arm_hps_hps_io (
		output wire [28:0] gpio_loanio_loanio0_i,     // gpio_loanio.loanio0_i
		input  wire [28:0] gpio_loanio_loanio0_oe,    //            .loanio0_oe
		input  wire [28:0] gpio_loanio_loanio0_o,     //            .loanio0_o
		output wire [28:0] gpio_loanio_loanio1_i,     //            .loanio1_i
		input  wire [28:0] gpio_loanio_loanio1_oe,    //            .loanio1_oe
		input  wire [28:0] gpio_loanio_loanio1_o,     //            .loanio1_o
		output wire [8:0]  gpio_loanio_loanio2_i,     //            .loanio2_i
		input  wire [8:0]  gpio_loanio_loanio2_oe,    //            .loanio2_oe
		input  wire [8:0]  gpio_loanio_loanio2_o,     //            .loanio2_o
		output wire [14:0] mem_a,                     //      memory.mem_a
		output wire [2:0]  mem_ba,                    //            .mem_ba
		output wire        mem_ck,                    //            .mem_ck
		output wire        mem_ck_n,                  //            .mem_ck_n
		output wire        mem_cke,                   //            .mem_cke
		output wire        mem_cs_n,                  //            .mem_cs_n
		output wire        mem_ras_n,                 //            .mem_ras_n
		output wire        mem_cas_n,                 //            .mem_cas_n
		output wire        mem_we_n,                  //            .mem_we_n
		output wire        mem_reset_n,               //            .mem_reset_n
		inout  wire [31:0] mem_dq,                    //            .mem_dq
		inout  wire [3:0]  mem_dqs,                   //            .mem_dqs
		inout  wire [3:0]  mem_dqs_n,                 //            .mem_dqs_n
		output wire        mem_odt,                   //            .mem_odt
		output wire [3:0]  mem_dm,                    //            .mem_dm
		input  wire        oct_rzqin,                 //            .oct_rzqin
		inout  wire        hps_io_sdio_inst_CMD,      //      hps_io.hps_io_sdio_inst_CMD
		inout  wire        hps_io_sdio_inst_D0,       //            .hps_io_sdio_inst_D0
		inout  wire        hps_io_sdio_inst_D1,       //            .hps_io_sdio_inst_D1
		output wire        hps_io_sdio_inst_CLK,      //            .hps_io_sdio_inst_CLK
		inout  wire        hps_io_sdio_inst_D2,       //            .hps_io_sdio_inst_D2
		inout  wire        hps_io_sdio_inst_D3,       //            .hps_io_sdio_inst_D3
		inout  wire        hps_io_i2c0_inst_SDA,      //            .hps_io_i2c0_inst_SDA
		inout  wire        hps_io_i2c0_inst_SCL,      //            .hps_io_i2c0_inst_SCL
		inout  wire        hps_io_gpio_inst_GPIO48,   //            .hps_io_gpio_inst_GPIO48
		inout  wire        hps_io_gpio_inst_GPIO53,   //            .hps_io_gpio_inst_GPIO53
		inout  wire        hps_io_gpio_inst_GPIO54,   //            .hps_io_gpio_inst_GPIO54
		inout  wire        hps_io_gpio_inst_LOANIO49, //            .hps_io_gpio_inst_LOANIO49
		inout  wire        hps_io_gpio_inst_LOANIO50  //            .hps_io_gpio_inst_LOANIO50
	);

	HPSWrapper_arm_hps_hps_io_border border (
		.gpio_loanio_loanio0_i     (gpio_loanio_loanio0_i),     // gpio_loanio.loanio0_i
		.gpio_loanio_loanio0_oe    (gpio_loanio_loanio0_oe),    //            .loanio0_oe
		.gpio_loanio_loanio0_o     (gpio_loanio_loanio0_o),     //            .loanio0_o
		.gpio_loanio_loanio1_i     (gpio_loanio_loanio1_i),     //            .loanio1_i
		.gpio_loanio_loanio1_oe    (gpio_loanio_loanio1_oe),    //            .loanio1_oe
		.gpio_loanio_loanio1_o     (gpio_loanio_loanio1_o),     //            .loanio1_o
		.gpio_loanio_loanio2_i     (gpio_loanio_loanio2_i),     //            .loanio2_i
		.gpio_loanio_loanio2_oe    (gpio_loanio_loanio2_oe),    //            .loanio2_oe
		.gpio_loanio_loanio2_o     (gpio_loanio_loanio2_o),     //            .loanio2_o
		.mem_a                     (mem_a),                     //      memory.mem_a
		.mem_ba                    (mem_ba),                    //            .mem_ba
		.mem_ck                    (mem_ck),                    //            .mem_ck
		.mem_ck_n                  (mem_ck_n),                  //            .mem_ck_n
		.mem_cke                   (mem_cke),                   //            .mem_cke
		.mem_cs_n                  (mem_cs_n),                  //            .mem_cs_n
		.mem_ras_n                 (mem_ras_n),                 //            .mem_ras_n
		.mem_cas_n                 (mem_cas_n),                 //            .mem_cas_n
		.mem_we_n                  (mem_we_n),                  //            .mem_we_n
		.mem_reset_n               (mem_reset_n),               //            .mem_reset_n
		.mem_dq                    (mem_dq),                    //            .mem_dq
		.mem_dqs                   (mem_dqs),                   //            .mem_dqs
		.mem_dqs_n                 (mem_dqs_n),                 //            .mem_dqs_n
		.mem_odt                   (mem_odt),                   //            .mem_odt
		.mem_dm                    (mem_dm),                    //            .mem_dm
		.oct_rzqin                 (oct_rzqin),                 //            .oct_rzqin
		.hps_io_sdio_inst_CMD      (hps_io_sdio_inst_CMD),      //      hps_io.hps_io_sdio_inst_CMD
		.hps_io_sdio_inst_D0       (hps_io_sdio_inst_D0),       //            .hps_io_sdio_inst_D0
		.hps_io_sdio_inst_D1       (hps_io_sdio_inst_D1),       //            .hps_io_sdio_inst_D1
		.hps_io_sdio_inst_CLK      (hps_io_sdio_inst_CLK),      //            .hps_io_sdio_inst_CLK
		.hps_io_sdio_inst_D2       (hps_io_sdio_inst_D2),       //            .hps_io_sdio_inst_D2
		.hps_io_sdio_inst_D3       (hps_io_sdio_inst_D3),       //            .hps_io_sdio_inst_D3
		.hps_io_i2c0_inst_SDA      (hps_io_i2c0_inst_SDA),      //            .hps_io_i2c0_inst_SDA
		.hps_io_i2c0_inst_SCL      (hps_io_i2c0_inst_SCL),      //            .hps_io_i2c0_inst_SCL
		.hps_io_gpio_inst_GPIO48   (hps_io_gpio_inst_GPIO48),   //            .hps_io_gpio_inst_GPIO48
		.hps_io_gpio_inst_GPIO53   (hps_io_gpio_inst_GPIO53),   //            .hps_io_gpio_inst_GPIO53
		.hps_io_gpio_inst_GPIO54   (hps_io_gpio_inst_GPIO54),   //            .hps_io_gpio_inst_GPIO54
		.hps_io_gpio_inst_LOANIO49 (hps_io_gpio_inst_LOANIO49), //            .hps_io_gpio_inst_LOANIO49
		.hps_io_gpio_inst_LOANIO50 (hps_io_gpio_inst_LOANIO50)  //            .hps_io_gpio_inst_LOANIO50
	);

endmodule
