set_false_path -from [get_ports hps_io_hps_io_sdio_inst_CMD] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CMD]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D0]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D1]
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CLK]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D2]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D3]
set_false_path -from [get_ports hps_io_hps_io_i2c0_inst_SDA] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_i2c0_inst_SDA]
set_false_path -from [get_ports hps_io_hps_io_i2c0_inst_SCL] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_i2c0_inst_SCL]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO48] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO48]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO53] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO53]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO54] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO54]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO49] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO49]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO50] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO50]